# Generated by Django 4.0.6 on 2022-08-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
