# Generated by Django 4.1.3 on 2022-11-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(db_column='doctorID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(db_column='phoneNumber', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('office', models.CharField(max_length=255)),
                ('photo', models.TextField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_name', models.CharField(db_column='officeName', max_length=255, primary_key=True, serialize=False)),
                ('head_id', models.CharField(blank=True, db_column='headID', max_length=10, null=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(db_column='patientID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(db_column='phoneNumber', max_length=13)),
                ('history', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.TextField()),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PaymentSlip',
            fields=[
                ('payment_id', models.CharField(db_column='paymentID', max_length=10, primary_key=True, serialize=False)),
                ('payment_items', models.CharField(db_column='paymentItems', max_length=2)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField()),
                ('patient_id', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'db_table': 'payment_slip',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSlip',
            fields=[
                ('registration_id', models.CharField(db_column='registrationID', max_length=10, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('type', models.CharField(max_length=4)),
                ('doctor_id', models.ForeignKey(db_column='doctorID', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('office', models.ForeignKey(db_column='office', on_delete=django.db.models.deletion.CASCADE, to='hospital.office')),
                ('patient_id', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('payment_id', models.ForeignKey(db_column='paymentID', on_delete=django.db.models.deletion.CASCADE, to='hospital.paymentslip')),
            ],
            options={
                'db_table': 'registration_slip',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionList',
            fields=[
                ('prescription_id', models.CharField(db_column='prescriptionID', max_length=10, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('doctor_id', models.ForeignKey(db_column='doctorID', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient_id', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
                ('payment_id', models.ForeignKey(db_column='paymentID', on_delete=django.db.models.deletion.CASCADE, to='hospital.paymentslip')),
            ],
            options={
                'db_table': 'prescription_list',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('medical_records_id', models.CharField(db_column='medicalRecordsID', max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('treatment_programme', models.TextField(db_column='treatmentProgramme')),
                ('diagnoses', models.TextField(db_column='Diagnoses')),
                ('doctor_id', models.ForeignKey(db_column='doctorID', on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('office', models.ForeignKey(db_column='office', on_delete=django.db.models.deletion.CASCADE, to='hospital.office')),
                ('patient_id', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('inspection_id', models.CharField(db_column='inspectionID', max_length=12, primary_key=True, serialize=False)),
                ('inspection_name', models.CharField(db_column='InspectionName', max_length=255)),
                ('result', models.TextField()),
                ('analysis', models.TextField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('medical_records_id', models.ForeignKey(db_column='medicalRecordsID', on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalrecords')),
                ('payment_id', models.ForeignKey(db_column='paymentID', on_delete=django.db.models.deletion.CASCADE, to='hospital.paymentslip')),
            ],
            options={
                'db_table': 'inspection_item',
            },
        ),
    ]
