# Generated by Django 4.1.3 on 2022-11-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalRecords',
            new_name='MedicalRecord',
        ),
    ]
