# Generated by Django 4.1.3 on 2022-11-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentslip",
            name="has_pay",
            field=models.CharField(db_column="haspay", max_length=1),
        ),
    ]
